-- ============================================================================
-- Cleanup Performance Test Data
-- ============================================================================
-- Removes all test data generated by generate_test_data.sql
-- Safe to run multiple times
--
-- Usage: psql -d accounting -f cleanup_test_data.sql
-- ============================================================================

\set ON_ERROR_STOP on
\timing on

DO $$
DECLARE
    v_voucher_count INTEGER;
    v_je_count INTEGER;
    v_customer_count INTEGER;
    v_supplier_count INTEGER;
BEGIN
    RAISE NOTICE 'Starting cleanup of performance test data...';
    
    -- Count before cleanup
    SELECT COUNT(*) INTO v_voucher_count FROM vouchers WHERE voucher_number LIKE 'PERF-%';
    SELECT COUNT(*) INTO v_customer_count FROM customers WHERE code LIKE 'CUST-PERF-%';
    SELECT COUNT(*) INTO v_supplier_count FROM suppliers WHERE code LIKE 'SUP-PERF-%';
    
    RAISE NOTICE 'Found % vouchers, % customers, % suppliers to delete', 
        v_voucher_count, v_customer_count, v_supplier_count;
    
    -- Delete journal entries (cascade from vouchers)
    DELETE FROM journal_entries 
    WHERE voucher_id IN (SELECT id FROM vouchers WHERE voucher_number LIKE 'PERF-%');
    GET DIAGNOSTICS v_je_count = ROW_COUNT;
    RAISE NOTICE 'Deleted % journal entries', v_je_count;
    
    -- Delete vouchers
    DELETE FROM vouchers WHERE voucher_number LIKE 'PERF-%';
    GET DIAGNOSTICS v_voucher_count = ROW_COUNT;
    RAISE NOTICE 'Deleted % vouchers', v_voucher_count;
    
    -- Delete test customers
    DELETE FROM customers WHERE code LIKE 'CUST-PERF-%';
    GET DIAGNOSTICS v_customer_count = ROW_COUNT;
    RAISE NOTICE 'Deleted % customers', v_customer_count;
    
    -- Delete test suppliers
    DELETE FROM suppliers WHERE code LIKE 'SUP-PERF-%';
    GET DIAGNOSTICS v_supplier_count = ROW_COUNT;
    RAISE NOTICE 'Deleted % suppliers', v_supplier_count;
    
    -- Refresh materialized views
    RAISE NOTICE 'Refreshing materialized views...';
    REFRESH MATERIALIZED VIEW mv_daily_revenue_expense;
    REFRESH MATERIALIZED VIEW mv_ar_ap_aging;
    REFRESH MATERIALIZED VIEW mv_cash_flow_summary;
    REFRESH MATERIALIZED VIEW mv_period_summary;
    REFRESH MATERIALIZED VIEW mv_top_debtors_creditors;
    
    RAISE NOTICE 'Cleanup complete!';
END $$;

-- Verify cleanup
SELECT 'Remaining test data:' AS status;
SELECT 'vouchers' AS table_name, COUNT(*) AS count FROM vouchers WHERE voucher_number LIKE 'PERF-%'
UNION ALL
SELECT 'customers', COUNT(*) FROM customers WHERE code LIKE 'CUST-PERF-%'
UNION ALL
SELECT 'suppliers', COUNT(*) FROM suppliers WHERE code LIKE 'SUP-PERF-%';
