package com.accounting.dto.analytics;

import java.time.LocalDateTime;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Metadata for exported analytics dashboard with TT200 compliance watermark")
public record ExportMetadata(
        @Schema(description = "Company ID the export belongs to") Long companyId,
        @Schema(description = "Accounting period ID") java.util.UUID periodId,
        @Schema(
                        description = "Dashboard type",
                        example = "FINANCIAL_OVERVIEW",
                        allowableValues = {"FINANCIAL_OVERVIEW", "AR_AP_AGING", "CASH_FLOW", "PERIOD_SUMMARY"})
                String dashboardType,
        @Schema(description = "Export format", example = "EXCEL", allowableValues = {"EXCEL", "PDF"}) String format,
        @Schema(description = "Number of data rows in export", example = "150") int rowCount,
        @Schema(description = "Timestamp when export was generated") LocalDateTime generatedAt,
        @Schema(description = "Name of user who generated the export", example = "Nguyen Van A") String generatedBy,
        @Schema(description = "TT200 compliance watermark text", example = "CONFIDENTIAL - Generated by Nguyen Van A")
                String watermark) {}
