package com.accounting.service.impl.sales;

import static org.assertj.core.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

import com.accounting.dto.*;
import com.accounting.entity.*;
import com.accounting.repository.*;
import com.accounting.security.CompanyContext;
import com.accounting.security.SecurityUtils;
import com.accounting.service.*;
import com.accounting.service.voucher.VoucherPostingService;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.persistence.EntityManager;
import jakarta.persistence.criteria.CriteriaBuilder;
import jakarta.persistence.criteria.CriteriaQuery;
import jakarta.persistence.criteria.Predicate;
import jakarta.persistence.criteria.Root;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.*;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;

/**
 * Unit tests for ReceiptServiceImpl.
 * 
 * Test coverage:
 * - Receipt CRUD operations
 * - Allocation logic and validation
 * - Posting with GL voucher generation
 * - Reversal with audit trail
 * - Business rule validations
 */
@ExtendWith(MockitoExtension.class)
class ReceiptServiceImplTest {

  @Mock
  private ARPaymentRepository receiptRepository;
  @Mock
  private ReceiptAllocationRepository allocationRepository;
  @Mock
  private SalesInvoiceRepository salesInvoiceRepository;
  @Mock
  private CustomerRepository customerRepository;
  @Mock
  private BankAccountRepository bankAccountRepository;
  @Mock
  private UserRepository userRepository;
  @Mock
  private ChartOfAccountsRepository chartOfAccountsRepository;
  @Mock
  private ReceiptValidationService receiptValidationService;
  @Mock
  private VoucherService voucherService;
  @Mock
  private VoucherPostingService voucherPostingService;
  @Mock
  private AuditService auditService;
  @Mock
  private CompanySettingsService companySettingsService;
  @Mock
  private ObjectMapper objectMapper;
  @Mock
  private EntityManager entityManager;

  @InjectMocks
  private ReceiptServiceImpl receiptService;

  private MockedStatic<SecurityUtils> securityUtilsMock;

  private static final Long COMPANY_ID = 1L;
  private static final Long USER_ID = 100L;
  private static final Long CUSTOMER_ID = 200L;
  private static final Long BANK_ACCOUNT_ID = 300L;

  @BeforeEach
  void setUp() {
    CompanyContext.setCompanyId(COMPANY_ID);
    securityUtilsMock = mockStatic(SecurityUtils.class);
    securityUtilsMock.when(SecurityUtils::getCurrentUserId).thenReturn(USER_ID);
  }

  @AfterEach
  void tearDown() {
    CompanyContext.clear();
    if (securityUtilsMock != null) {
      securityUtilsMock.close();
    }
  }

  @Nested
  @DisplayName("Receipt Creation Tests")
  class ReceiptCreationTests {

    @Test
    @DisplayName("Should create receipt with auto-generated number")
    void shouldCreateReceiptWithAutoGeneratedNumber() {
      // GIVEN
      ARPaymentCreateRequest request = createValidRequest();
      Customer customer = createMockCustomer();
      BankAccount bankAccount = createMockBankAccount();
      User user = createMockUser();

      when(customerRepository.findByCompanyIdAndId(COMPANY_ID, CUSTOMER_ID)).thenReturn(Optional.of(customer));
      when(bankAccountRepository.findByCompanyIdAndId(COMPANY_ID, BANK_ACCOUNT_ID))
          .thenReturn(Optional.of(bankAccount));
      when(userRepository.findById(USER_ID)).thenReturn(Optional.of(user));
      when(receiptRepository.save(any(ARPayment.class))).thenAnswer(inv -> {
        ARPayment receipt = inv.getArgument(0);
        receipt.setId(UUID.randomUUID());
        return receipt;
      });

      // Mock complete JPA Criteria API chain for receipt number generation
      mockReceiptNumberGeneration(Collections.emptyList());

      // WHEN
      ARPaymentDTO result = receiptService.create(request);

      // THEN
      assertNotNull(result);
      verify(receiptRepository).save(any(ARPayment.class));
      // Audit logging verified in integration tests
    }

    @Test
    @DisplayName("Should validate customer exists when creating receipt")
    void shouldValidateCustomerExistsWhenCreating() {
      // GIVEN
      ARPaymentCreateRequest request = createValidRequest();
      when(customerRepository.findByCompanyIdAndId(COMPANY_ID, CUSTOMER_ID)).thenReturn(Optional.empty());

      // WHEN/THEN
      assertThrows(ResponseStatusException.class, () -> receiptService.create(request));
      verify(receiptRepository, never()).save(any());
    }

    @Test
    @DisplayName("Should validate bank account exists when creating receipt")
    void shouldValidateBankAccountExistsWhenCreating() {
      // GIVEN
      ARPaymentCreateRequest request = createValidRequest();
      Customer customer = createMockCustomer();

      when(customerRepository.findByCompanyIdAndId(COMPANY_ID, CUSTOMER_ID)).thenReturn(Optional.of(customer));
      when(bankAccountRepository.findByCompanyIdAndId(COMPANY_ID, BANK_ACCOUNT_ID)).thenReturn(Optional.empty());

      // WHEN/THEN
      assertThrows(ResponseStatusException.class, () -> receiptService.create(request));
      verify(receiptRepository, never()).save(any());
    }

    @Test
    @DisplayName("Should generate receipt number with correct format")
    void shouldGenerateReceiptNumberWithCorrectFormat() {
      // GIVEN
      LocalDate receiptDate = LocalDate.of(2025, 1, 15);
      mockReceiptNumberGeneration(List.of("RCP-2025-00005"));

      // WHEN
      String receiptNumber = receiptService.generateReceiptNumber(receiptDate);

      // THEN
      assertThat(receiptNumber).startsWith("RCP-2025-");
      assertThat(receiptNumber).isEqualTo("RCP-2025-00006");
    }
  }

  @Nested
  @DisplayName("Receipt Update Tests")
  class ReceiptUpdateTests {

    @Test
    @DisplayName("Should update DRAFT receipt")
    void shouldUpdateDraftReceipt() {
      // GIVEN
      UUID receiptId = UUID.randomUUID();
      ARPayment existingReceipt = createMockReceipt(ReceiptStatus.DRAFT);
      ARPaymentCreateRequest request = createValidRequest();
      request.setAmount(BigDecimal.valueOf(2_000_000));

      when(receiptRepository.findByCompanyIdAndId(COMPANY_ID, receiptId)).thenReturn(Optional.of(existingReceipt));
      // Validation service mocks not needed as validation happens inside service but
      // we are not testing validation here
      when(receiptRepository.save(any(ARPayment.class))).thenAnswer(inv -> inv.getArgument(0));

      // WHEN
      ARPaymentDTO result = receiptService.update(receiptId, request);

      // THEN
      assertNotNull(result);
      verify(receiptRepository)
          .save(argThat(receipt -> receipt.getAmount().compareTo(BigDecimal.valueOf(2_000_000)) == 0));
      // Audit logging verified in integration tests
    }

    @Test
    @DisplayName("Should reject update of POSTED receipt")
    void shouldRejectUpdateOfPostedReceipt() {
      // GIVEN
      UUID receiptId = UUID.randomUUID();
      ARPayment existingReceipt = createMockReceipt(ReceiptStatus.POSTED);
      ARPaymentCreateRequest request = createValidRequest();

      when(receiptRepository.findByCompanyIdAndId(COMPANY_ID, receiptId)).thenReturn(Optional.of(existingReceipt));

      // WHEN/THEN
      ResponseStatusException exception = assertThrows(
          ResponseStatusException.class,
          () -> receiptService.update(receiptId, request));
      assertThat(exception.getStatusCode()).isEqualTo(HttpStatus.CONFLICT);
      verify(receiptRepository, never()).save(any());
    }
  }

  @Nested
  @DisplayName("Receipt Deletion Tests")
  class ReceiptDeletionTests {

    @Test
    @DisplayName("Should delete DRAFT receipt")
    void shouldDeleteDraftReceipt() {
      // GIVEN
      UUID receiptId = UUID.randomUUID();
      ARPayment receipt = createMockReceipt(ReceiptStatus.DRAFT);

      when(receiptRepository.findByCompanyIdAndId(COMPANY_ID, receiptId)).thenReturn(Optional.of(receipt));
      doNothing().when(receiptRepository).delete(any(ARPayment.class));

      // WHEN
      receiptService.delete(receiptId);

      // THEN
      verify(receiptRepository).delete(eq(receipt));
      // Audit logging verified in integration tests
    }

    @Test
    @DisplayName("Should reject deletion of POSTED receipt")
    void shouldRejectDeletionOfPostedReceipt() {
      // GIVEN
      UUID receiptId = UUID.randomUUID();
      ARPayment receipt = createMockReceipt(ReceiptStatus.POSTED);

      when(receiptRepository.findByCompanyIdAndId(COMPANY_ID, receiptId)).thenReturn(Optional.of(receipt));

      // WHEN/THEN
      ResponseStatusException exception = assertThrows(
          ResponseStatusException.class,
          () -> receiptService.delete(receiptId));
      assertThat(exception.getStatusCode()).isEqualTo(HttpStatus.CONFLICT);
      verify(receiptRepository, never()).delete(any(ARPayment.class));
    }
  }

  @Nested
  @DisplayName("Receipt Allocation Tests")
  class ReceiptAllocationTests {

    @Test
    @DisplayName("Should allocate receipt to single invoice")
    void shouldAllocateReceiptToSingleInvoice() {
      // GIVEN
      UUID receiptId = UUID.randomUUID();
      UUID invoiceId = UUID.randomUUID();
      ARPayment receipt = createMockReceipt(ReceiptStatus.DRAFT);
      receipt.setAmount(BigDecimal.valueOf(5_000_000));

      SalesInvoice invoice = createMockInvoice(invoiceId, BigDecimal.valueOf(5_000_000));

      List<ReceiptAllocationRequest> allocations = List.of(
          new ReceiptAllocationRequest(invoiceId, BigDecimal.valueOf(5_000_000)));

      when(receiptRepository.findByCompanyIdAndId(COMPANY_ID, receiptId)).thenReturn(Optional.of(receipt));
      lenient().when(salesInvoiceRepository.findById(invoiceId)).thenReturn(Optional.of(invoice));

      // Mock validation
      ReceiptValidationResult validationResult = new ReceiptValidationResult();
      validationResult.setValid(true);
      when(receiptValidationService.validateAllocations(any(), any())).thenReturn(validationResult);

      when(allocationRepository.save(any())).thenAnswer(inv -> inv.getArgument(0));
      when(receiptRepository.save(any(ARPayment.class))).thenAnswer(inv -> inv.getArgument(0));

      // WHEN
      ARPaymentDTO result = receiptService.allocateInvoices(receiptId, allocations);

      // THEN
      assertNotNull(result);
      verify(allocationRepository).save(any(ReceiptAllocation.class));
      // Audit logging verified in integration tests
    }

    @Test
    @DisplayName("Should allocate receipt to multiple invoices")
    void shouldAllocateReceiptToMultipleInvoices() {
      // GIVEN
      UUID receiptId = UUID.randomUUID();
      UUID invoice1Id = UUID.randomUUID();
      UUID invoice2Id = UUID.randomUUID();

      ARPayment receipt = createMockReceipt(ReceiptStatus.DRAFT);
      receipt.setAmount(BigDecimal.valueOf(10_000_000));

      SalesInvoice invoice1 = createMockInvoice(invoice1Id, BigDecimal.valueOf(6_000_000));
      SalesInvoice invoice2 = createMockInvoice(invoice2Id, BigDecimal.valueOf(4_000_000));

      List<ReceiptAllocationRequest> allocations = List.of(
          new ReceiptAllocationRequest(invoice1Id, BigDecimal.valueOf(6_000_000)),
          new ReceiptAllocationRequest(invoice2Id, BigDecimal.valueOf(4_000_000)));

      when(receiptRepository.findByCompanyIdAndId(COMPANY_ID, receiptId)).thenReturn(Optional.of(receipt));
      lenient().when(salesInvoiceRepository.findById(invoice1Id)).thenReturn(Optional.of(invoice1));
      lenient().when(salesInvoiceRepository.findById(invoice2Id)).thenReturn(Optional.of(invoice2));

      // Mock validation
      ReceiptValidationResult validationResult = new ReceiptValidationResult();
      validationResult.setValid(true);
      when(receiptValidationService.validateAllocations(any(), any())).thenReturn(validationResult);

      when(allocationRepository.save(any())).thenAnswer(inv -> inv.getArgument(0));
      when(receiptRepository.save(any(ARPayment.class))).thenAnswer(inv -> inv.getArgument(0));

      // WHEN
      ARPaymentDTO result = receiptService.allocateInvoices(receiptId, allocations);

      // THEN
      assertNotNull(result);
      verify(allocationRepository, times(2)).save(any(ReceiptAllocation.class));
    }

    @Test
    @DisplayName("Should prevent overpayment allocation")
    void shouldPreventOverpaymentAllocation() {
      // GIVEN
      UUID receiptId = UUID.randomUUID();
      UUID invoiceId = UUID.randomUUID();
      ARPayment receipt = createMockReceipt(ReceiptStatus.DRAFT);
      receipt.setAmount(BigDecimal.valueOf(3_000_000));

      SalesInvoice invoice = createMockInvoice(invoiceId, BigDecimal.valueOf(5_000_000));

      List<ReceiptAllocationRequest> allocations = List.of(
          new ReceiptAllocationRequest(invoiceId, BigDecimal.valueOf(5_000_000)) // More than receipt amount
      );

      when(receiptRepository.findByCompanyIdAndId(COMPANY_ID, receiptId)).thenReturn(Optional.of(receipt));
      lenient().when(salesInvoiceRepository.findById(invoiceId)).thenReturn(Optional.of(invoice));

      // Mock validation to reject overpayment
      ReceiptValidationResult validationResult = new ReceiptValidationResult();
      validationResult.addFieldError("allocations", "Total allocated amount exceeds receipt amount");
      when(receiptValidationService.validateAllocations(any(), any())).thenReturn(validationResult);

      // WHEN/THEN
      assertThrows(ResponseStatusException.class,
          () -> receiptService.allocateInvoices(receiptId, allocations));
      verify(allocationRepository, never()).save(any());
    }

    @Test
    @DisplayName("Should update existing allocations for DRAFT receipt")
    void shouldUpdateExistingAllocationsForDraftReceipt() {
      // GIVEN
      UUID receiptId = UUID.randomUUID();
      UUID invoiceId = UUID.randomUUID();
      ARPayment receipt = createMockReceipt(ReceiptStatus.DRAFT);
      receipt.setAmount(BigDecimal.valueOf(5_000_000));

      SalesInvoice invoice = createMockInvoice(invoiceId, BigDecimal.valueOf(5_000_000));

      List<ReceiptAllocationRequest> newAllocations = List.of(
          new ReceiptAllocationRequest(invoiceId, BigDecimal.valueOf(3_000_000)));

      when(receiptRepository.findByCompanyIdAndId(COMPANY_ID, receiptId)).thenReturn(Optional.of(receipt));
      lenient().when(salesInvoiceRepository.findById(invoiceId)).thenReturn(Optional.of(invoice));
      doNothing().when(allocationRepository).deleteByReceiptId(receiptId);

      // Mock validation
      ReceiptValidationResult validationResult = new ReceiptValidationResult();
      validationResult.setValid(true);
      when(receiptValidationService.validateAllocations(any(), any())).thenReturn(validationResult);

      when(allocationRepository.save(any())).thenAnswer(inv -> inv.getArgument(0));
      when(receiptRepository.save(any(ARPayment.class))).thenAnswer(inv -> inv.getArgument(0));

      // WHEN
      ARPaymentDTO result = receiptService.updateAllocations(receiptId, newAllocations);

      // THEN
      assertNotNull(result);
      verify(allocationRepository).deleteByReceiptId(receiptId);
      verify(allocationRepository).save(any(ReceiptAllocation.class));
    }
  }

  @Nested
  @DisplayName("Receipt Posting Tests")
  class ReceiptPostingTests {

    @Test
    @DisplayName("Should post receipt and generate GL voucher")
    void shouldPostReceiptAndGenerateGLVoucher() {
      // GIVEN
      UUID receiptId = UUID.randomUUID();
      UUID voucherId = UUID.randomUUID();
      ARPayment receipt = createMockReceipt(ReceiptStatus.DRAFT);
      receipt.setAmount(BigDecimal.valueOf(5_000_000));

      UUID invoiceId = UUID.randomUUID();
      SalesInvoice invoice = createMockInvoice(invoiceId, BigDecimal.valueOf(5_000_000));

      ReceiptAllocation allocation = new ReceiptAllocation();
      allocation.setSalesInvoiceId(invoiceId);
      allocation.setAllocatedAmount(BigDecimal.valueOf(5_000_000));

      VoucherDTO voucherDTO = new VoucherDTO();
      voucherDTO.setId(voucherId);

      ChartOfAccount arAccount = new ChartOfAccount();
      arAccount.setId(1000L);
      arAccount.setCode("131");

      when(receiptRepository.findByCompanyIdAndId(COMPANY_ID, receiptId)).thenReturn(Optional.of(receipt));
      when(allocationRepository.findByReceiptIdOrderByAllocationOrderAsc(receiptId))
          .thenReturn(List.of(allocation));
      when(salesInvoiceRepository.findById(invoiceId)).thenReturn(Optional.of(invoice));
      when(allocationRepository.sumAllocatedAmountBySalesInvoiceIdAndPostedReceipts(invoiceId))
          .thenReturn(BigDecimal.valueOf(5_000_000));
      when(chartOfAccountsRepository.findByCompanyIdAndCode(COMPANY_ID, "131"))
          .thenReturn(Optional.of(arAccount));
      // Skip validation in unit test
      when(voucherService.create(any(VoucherCreateRequest.class))).thenReturn(voucherDTO);
      when(receiptRepository.save(any())).thenAnswer(inv -> inv.getArgument(0));

      // WHEN
      ARPaymentDTO result = receiptService.postReceipt(receiptId);

      // THEN
      assertNotNull(result);
      verify(voucherService).create(any(VoucherCreateRequest.class));
      verify(receiptRepository)
          .save(argThat(r -> r.getStatus() == ReceiptStatus.POSTED && r.getLinkedVoucherId() != null));
      // Audit logging verified in integration tests
    }

    @Test
    @DisplayName("Should update invoice status to PAID when fully allocated")
    void shouldUpdateInvoiceStatusToPaidWhenFullyAllocated() {
      // GIVEN
      UUID receiptId = UUID.randomUUID();
      UUID invoiceId = UUID.randomUUID();
      ARPayment receipt = createMockReceipt(ReceiptStatus.DRAFT);
      receipt.setAmount(BigDecimal.valueOf(5_000_000));

      SalesInvoice invoice = createMockInvoice(invoiceId, BigDecimal.valueOf(5_000_000));

      ReceiptAllocation allocation = new ReceiptAllocation();
      allocation.setSalesInvoiceId(invoiceId);
      allocation.setAllocatedAmount(BigDecimal.valueOf(5_000_000));

      ChartOfAccount arAccount = new ChartOfAccount();
      arAccount.setId(1000L);
      arAccount.setCode("131");

      when(receiptRepository.findByCompanyIdAndId(COMPANY_ID, receiptId)).thenReturn(Optional.of(receipt));
      when(allocationRepository.findByReceiptIdOrderByAllocationOrderAsc(receiptId))
          .thenReturn(List.of(allocation));
      when(salesInvoiceRepository.findById(invoiceId)).thenReturn(Optional.of(invoice));
      when(allocationRepository.sumAllocatedAmountBySalesInvoiceIdAndPostedReceipts(invoiceId))
          .thenReturn(BigDecimal.valueOf(5_000_000));
      when(chartOfAccountsRepository.findByCompanyIdAndCode(COMPANY_ID, "131"))
          .thenReturn(Optional.of(arAccount));
      when(voucherService.create(any())).thenReturn(new VoucherDTO());
      when(receiptRepository.save(any())).thenAnswer(inv -> inv.getArgument(0));
      when(salesInvoiceRepository.save(any())).thenAnswer(inv -> inv.getArgument(0));

      // WHEN
      receiptService.postReceipt(receiptId);

      // THEN
      verify(salesInvoiceRepository, atLeastOnce()).save(any(SalesInvoice.class));
    }

    @Test
    @DisplayName("Should reject posting of already POSTED receipt")
    void shouldRejectPostingOfAlreadyPostedReceipt() {
      // GIVEN
      UUID receiptId = UUID.randomUUID();
      ARPayment receipt = createMockReceipt(ReceiptStatus.POSTED);

      when(receiptRepository.findByCompanyIdAndId(COMPANY_ID, receiptId)).thenReturn(Optional.of(receipt));

      // WHEN/THEN
      ResponseStatusException exception = assertThrows(
          ResponseStatusException.class,
          () -> receiptService.postReceipt(receiptId));
      assertThat(exception.getStatusCode()).isEqualTo(HttpStatus.CONFLICT);
      verify(voucherService, never()).create(any());
    }
  }

  @Nested
  @DisplayName("Receipt Reversal Tests")
  class ReceiptReversalTests {

    @Test
    @DisplayName("Should reverse POSTED receipt with mandatory reason")
    void shouldReversePostedReceiptWithMandatoryReason() {
      // GIVEN
      UUID receiptId = UUID.randomUUID();
      ARPayment receipt = createMockReceipt(ReceiptStatus.POSTED);
      receipt.setLinkedVoucherId(UUID.randomUUID());
      String reason = "Customer requested refund";

      when(receiptRepository.findByCompanyIdAndId(COMPANY_ID, receiptId)).thenReturn(Optional.of(receipt));
      when(voucherService.create(any())).thenReturn(new VoucherDTO());
      when(receiptRepository.save(any())).thenAnswer(inv -> inv.getArgument(0));

      // Mock receipt number generation for reversal receipt
      mockReceiptNumberGeneration(Collections.emptyList());

      // WHEN
      ARPaymentDTO result = receiptService.reverseReceipt(receiptId, reason);

      // THEN
      assertNotNull(result);
      verify(receiptRepository, atLeastOnce()).save(any(ARPayment.class));
      // Audit logging verified in integration tests
    }

    @Test
    @DisplayName("Should reject reversal without reason")
    void shouldRejectReversalWithoutReason() {
      // GIVEN
      UUID receiptId = UUID.randomUUID();
      ARPayment receipt = createMockReceipt(ReceiptStatus.POSTED);
      String emptyReason = "";

      when(receiptRepository.findByCompanyIdAndId(COMPANY_ID, receiptId)).thenReturn(Optional.of(receipt));

      // WHEN/THEN
      ResponseStatusException exception = assertThrows(
          ResponseStatusException.class,
          () -> receiptService.reverseReceipt(receiptId, emptyReason));
      assertThat(exception.getMessage()).contains("reason");
      verify(receiptRepository, never()).save(any());
    }

    @Test
    @DisplayName("Should reject reversal of DRAFT receipt")
    void shouldRejectReversalOfDraftReceipt() {
      // GIVEN
      UUID receiptId = UUID.randomUUID();
      ARPayment receipt = createMockReceipt(ReceiptStatus.DRAFT);
      String reason = "Test reason";

      when(receiptRepository.findByCompanyIdAndId(COMPANY_ID, receiptId)).thenReturn(Optional.of(receipt));

      // WHEN/THEN
      ResponseStatusException exception = assertThrows(
          ResponseStatusException.class,
          () -> receiptService.reverseReceipt(receiptId, reason));
      assertThat(exception.getStatusCode()).isEqualTo(HttpStatus.CONFLICT);
      verify(voucherService, never()).create(any());
    }

    @Test
    @DisplayName("Should reject reversal of already REVERSED receipt")
    void shouldRejectReversalOfAlreadyReversedReceipt() {
      // GIVEN
      UUID receiptId = UUID.randomUUID();
      ARPayment receipt = createMockReceipt(ReceiptStatus.REVERSED);
      String reason = "Test reason";

      when(receiptRepository.findByCompanyIdAndId(COMPANY_ID, receiptId)).thenReturn(Optional.of(receipt));

      // WHEN/THEN
      ResponseStatusException exception = assertThrows(
          ResponseStatusException.class,
          () -> receiptService.reverseReceipt(receiptId, reason));
      assertThat(exception.getStatusCode()).isEqualTo(HttpStatus.CONFLICT);
    }
  }

  // Helper methods

  private ARPaymentCreateRequest createValidRequest() {
    ARPaymentCreateRequest request = new ARPaymentCreateRequest();
    request.setCustomerId(CUSTOMER_ID);
    request.setReceiptDate(LocalDate.now());
    request.setBankAccountId(BANK_ACCOUNT_ID);
    request.setAmount(BigDecimal.valueOf(1_000_000));
    request.setPaymentMethod(PaymentMethod.BANK_TRANSFER);
    request.setPayee("Test Customer");
    request.setIsStandalone(false);
    return request;
  }

  private ARPayment createMockReceipt(ReceiptStatus status) {
    ARPayment receipt = new ARPayment();
    receipt.setId(UUID.randomUUID());
    receipt.setCompanyId(COMPANY_ID);
    receipt.setCustomerId(CUSTOMER_ID);
    receipt.setReceiptNumber("RCP-2025-0001");
    receipt.setReceiptDate(LocalDate.now());
    receipt.setBankAccountId(BANK_ACCOUNT_ID);
    receipt.setAmount(BigDecimal.valueOf(1_000_000));
    receipt.setPaymentMethod(PaymentMethod.BANK_TRANSFER);
    receipt.setPayee("Test Customer");
    receipt.setStatus(status);
    receipt.setIsStandalone(false);
    receipt.setCreatedById(USER_ID);
    return receipt;
  }

  private Customer createMockCustomer() {
    Customer customer = new Customer();
    customer.setId(CUSTOMER_ID);
    customer.setCode("CUST-001");
    customer.setName("Test Customer");
    customer.setCompanyId(COMPANY_ID);
    return customer;
  }

  private BankAccount createMockBankAccount() {
    BankAccount account = new BankAccount();
    account.setId(BANK_ACCOUNT_ID);
    account.setAccountNumber("BANK-001");
    account.setBankName("Test Bank");
    account.setCompanyId(COMPANY_ID);
    account.setActive(true);
    return account;
  }

  private User createMockUser() {
    User user = new User();
    user.setId(USER_ID);
    user.setEmail("test@example.com");
    user.setFullName("Test User");
    user.setCompanyId(COMPANY_ID);
    return user;
  }

  private SalesInvoice createMockInvoice(UUID invoiceId, BigDecimal amount) {
    SalesInvoice invoice = new SalesInvoice();
    invoice.setId(invoiceId);
    invoice.setCompanyId(COMPANY_ID);
    invoice.setCustomerId(CUSTOMER_ID);
    invoice.setInvoiceNumber("INV-001");
    invoice.setTotalAmount(amount);
    invoice.setStatus(SalesInvoiceStatus.POSTED);
    return invoice;
  }

  /**
   * Helper method to mock the complete JPA Criteria API chain for receipt number
   * generation.
   * This avoids NullPointerException when generateReceiptNumber() is called.
   * 
   * @param existingNumbers List of existing receipt numbers (can be empty for
   *                        first receipt)
   */
  @SuppressWarnings("unchecked")
  private void mockReceiptNumberGeneration(List<String> existingNumbers) {
    CriteriaBuilder cb = mock(CriteriaBuilder.class);
    CriteriaQuery<String> query = mock(CriteriaQuery.class);
    Root<ARPayment> root = mock(Root.class);
    Predicate predicate = mock(Predicate.class);
    jakarta.persistence.TypedQuery<String> typedQuery = mock(jakarta.persistence.TypedQuery.class);

    // Use lenient() to avoid strict stubbing issues with JPA Criteria API
    lenient().when(entityManager.getCriteriaBuilder()).thenReturn(cb);
    lenient().when(cb.createQuery(String.class)).thenReturn(query);
    lenient().when(query.from(ARPayment.class)).thenReturn(root);
    lenient().when(root.get(anyString())).thenReturn(mock(jakarta.persistence.criteria.Path.class));
    lenient().when(query.select(any())).thenReturn(query);
    lenient().when(cb.equal(any(), any())).thenReturn(predicate);
    lenient().when(cb.like(any(), anyString())).thenReturn(predicate);
    lenient().when(cb.and(any(), any())).thenReturn(predicate);
    lenient().when(query.where(any(Predicate.class))).thenReturn(query);
    lenient().when(cb.desc(any())).thenReturn(mock(jakarta.persistence.criteria.Order.class));
    lenient().when(query.orderBy(any(jakarta.persistence.criteria.Order.class))).thenReturn(query);
    lenient().when(entityManager.createQuery(query)).thenReturn(typedQuery);
    lenient().when(typedQuery.setMaxResults(1)).thenReturn(typedQuery);
    lenient().when(typedQuery.getResultList()).thenReturn(existingNumbers);
  }
}
